# **Import data**

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 탈주_merged.csv to 탈주_merged.csv

In [ ]:
title = '탈주'
df = pd.read_csv(f'{title}_merged.csv')
df.head()

,Index,작성자,작성일,실제 작성일,별점,감상평,공감수,크롤링 날짜
0,1,minchae,NaN,NaN,5.0,죽음이 아닌 의미없는 삶을 두려워 하라,0,2024-10-18
1,2,문학동네 원숭이,NaN,NaN,4.0,규남이가 귀남이가 됐다가 추남이 되는 이야기,0,2024-10-18
2,3,일확천금,NaN,NaN,3.5,둘의 관계가 굉장해 엄청나~!\n사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 ...,0,2024-10-18
3,4,으아나,NaN,NaN,3.0,규남아 그래서 무슨 사랑을 했냐고 묻잔아.... 대답해.....,0,2024-10-18
4,5,양태욱,NaN,NaN,1.5,"재미도 없고 말도 안되고 결말도, 스토리도 너무 뻔한 영화",0,2024-10-18

In [ ]:
reviews = df[['Index', '감상평', '별점', '공감수']]

reviews

      Index                                                감상평     별점  공감수
0         1                              죽음이 아닌 의미없는 삶을 두려워 하라    5.0    0
1         2                           규남이가 귀남이가 됐다가 추남이 되는 이야기    4.0    0
2         3  둘의 관계가 굉장해 엄청나~!\n사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 ...    3.5    0
3         4                규남아 그래서 무슨 사랑을 했냐고 묻잔아.... 대답해.....    3.0    0
4         5                   재미도 없고 말도 안되고 결말도, 스토리도 너무 뻔한 영화    1.5    0
...     ...                                                ...    ...  ...
2849   2850                           짧은 러닝타임과 함께 킬링타임할 수 있을지.   별점없음    2
2850   2851                                      기대감이 아주 높아용~!  보고싶어요    0
2851   2852  "현재의 선택이 틀리지 않았음을 증명하라."\n\n구교환 배우는 장난 아니네...ㅋ...    3.5    8
2852   2853  놀애잘앙,,, 돌위아가,,, 삼진아웃반,,,\n외,엇덯해 이재훈과 구갼을 꼬셨슴니까,,,  보고싶어요    0
2853   2854                                        구교환은 추격 장인.    3.5    0

[2854 rows x 4 columns]

In [ ]:
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

Collecting git+https://github.com/haven-jeon/PyKoSpacing.git
  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-jnuhv8yz
  Running command git clone --filter=blob:none --quiet https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-jnuhv8yz
  Resolved https://github.com/haven-jeon/PyKoSpacing.git to commit b32a889cbd10b006d2f4aba118f0cd5b677e2979
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorflow>=2.16.2 in /usr/local/lib/python3.10/dist-packages (from pykospacing==0.5) (2.17.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from pykospacing==0.5) (3.11.0)
Collecting argparse>=1.1.0 (from pykospacing==0.5)
  Downloading argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from h5py>=3.10.0->pykospacing==0.5) (1.26.4)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (0.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (24.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (75.1.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (1.16.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (1.64.1)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (2.17.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (3.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow>=2.16.2->pykospacing==0.5) (0.37.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow>=2.16.2->pykospacing==0.5) (0.44.0)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow>=2.16.2->pykospacing==0.5) (13.9.2)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow>=2.16.2->pykospacing==0.5) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow>=2.16.2->pykospacing==0.5) (0.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow>=2.16.2->pykospacing==0.5) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow>=2.16.2->pykospacing==0.5) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow>=2.16.2->pykospacing==0.5) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow>=2.16.2->pykospacing==0.5) (2024.8.30)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow>=2.16.2->pykospacing==0.5) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow>=2.16.2->pykospacing==0.5) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow>=2.16.2->pykospacing==0.5) (3.0.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow>=2.16.2->pykospacing==0.5) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow>=2.16.2->pykospacing==0.5) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow>=2.16.2->pykospacing==0.5) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow>=2.16.2->pykospacing==0.5) (0.1.2)
Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Building wheels for collected packages: pykospacing
  Building wheel for pykospacing (setup.py) ... done
  Created wheel for pykospacing: filename=pykospacing-0.5-py3-none-any.whl size=2286921 sha256=2ec014155b86a3f3d8a0f6afcd9a5604ab34647d3dfb8826fe47dcd645ed66df
  Stored in directory: /tmp/pip-ephem-wheel-cache-5tisy4ck/wheels/76/b3/33/dda14886ee76b8e53eb05580a14dfcf9145e9eb9d282c53f28
Successfully built pykospacing
Installing collected packages: argparse, pykospacing
Successfully installed argparse-1.4.0 pykospacing-0.5

In [ ]:
#import할 패키지 목록
import re
import pandas as pd
from tqdm import tqdm
from konlpy.tag import Okt
from pykospacing import Spacing
from collections import Counter

In [ ]:
reviews

      Index                                                감상평     별점  공감수
0         1                              죽음이 아닌 의미없는 삶을 두려워 하라    5.0    0
1         2                           규남이가 귀남이가 됐다가 추남이 되는 이야기    4.0    0
2         3  둘의 관계가 굉장해 엄청나~!\n사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 ...    3.5    0
3         4                규남아 그래서 무슨 사랑을 했냐고 묻잔아.... 대답해.....    3.0    0
4         5                   재미도 없고 말도 안되고 결말도, 스토리도 너무 뻔한 영화    1.5    0
...     ...                                                ...    ...  ...
2849   2850                           짧은 러닝타임과 함께 킬링타임할 수 있을지.   별점없음    2
2850   2851                                      기대감이 아주 높아용~!  보고싶어요    0
2851   2852  "현재의 선택이 틀리지 않았음을 증명하라."\n\n구교환 배우는 장난 아니네...ㅋ...    3.5    8
2852   2853  놀애잘앙,,, 돌위아가,,, 삼진아웃반,,,\n외,엇덯해 이재훈과 구갼을 꼬셨슴니까,,,  보고싶어요    0
2853   2854                                        구교환은 추격 장인.    3.5    0

[2854 rows x 4 columns]

In [ ]:
#null값 확인
reviews.isnull().sum()

Index    0
감상평      0
별점       0
공감수      0
dtype: int64

In [ ]:
#중복행 확인
duplicates = reviews[reviews['감상평'].duplicated(keep=False)]
d = duplicates.sort_values(by='감상평');d

      Index                           감상평   별점  공감수
973     974  Сукин сын, которого я любилэ  2.5    1
2129   2130  Сукин сын, которого я любилэ  5.0    6
1589   1590                           구교환  2.0    0
736     737                           구교환  2.0    1
1627   1628                         구교환 짱  5.0    1
1491   1492                         구교환 짱  3.5    0
1147   1148                      구교환이 섹시함  3.0    2
992     993                      구교환이 섹시함  4.0    1
927     928                   내가 사랑했던 개자식  3.0    0
579     580                   내가 사랑했던 개자식  5.0    1
1421   1422                      마음껏 실패하라  3.5    0
1367   1368                      마음껏 실패하라  4.5    0
1431   1432                           아쉽다  2.5    0
326     327                           아쉽다  1.0    0
971     972                           재밌음  4.0    0
1976   1977                           재밌음  3.5    0
822     823         죽음이 아닌 의미 없는 삶을 두려워하라  3.0    0
1321   1322         죽음이 아닌 의미 없는 삶을 두려워하라  3.0    2
1105   1106         죽음이 아닌 의미 없는 삶을 두려워하라  3.0    3
2377   2378         죽음이 아닌 의미 없는 삶을 두려워하라  2.5    0
1983   1984         죽음이 아닌 의미 없는 삶을 두려워하라  4.0    0
1037   1038          죽음이 아닌 의미없는 삶을 두려워하라  4.0    0
122     123          죽음이 아닌 의미없는 삶을 두려워하라  2.5    0
1516   1517          죽음이 아닌 의미없는 삶을 두려워하라  3.5    1
1573   1574          죽음이 아닌 의미없는 삶을 두려워하라  3.5    0
1574   1575          죽음이 아닌 의미없는 삶을 두려워하라  3.5    0
816     817          죽음이 아닌 의미없는 삶을 두려워하라  3.0    0
19       20          죽음이 아닌 의미없는 삶을 두려워하라  4.5    0
1353   1354         죽음이 아닌 의미없는 삶을 두려워하라.  3.0    0
901     902         죽음이 아닌 의미없는 삶을 두려워하라.  3.0    5
373     374         죽음이 아닌 의미없는 삶을 두려워하라.  3.5    0
1843   1844                          행복하자  3.0    0
735     736                          행복하자  2.0    0
2353   2354                          행복하자  4.0    0
1818   1819                          행복하자  3.0    0
2675   2676                          행복하자  3.5    1
1947   1948                        환불해주세요  1.0    0
2549   2550                        환불해주세요  1.0    2

In [ ]:
# 10자 이상 중복된 행 필터링 및 삭제
duplicates = reviews[reviews['감상평'].duplicated(keep=False)]
to_drop = duplicates[duplicates['감상평'].str.len() >= 10].index
reviews = reviews.drop(to_drop)

# 인덱스 재배열
reviews = reviews.reset_index(drop=True);reviews

      Index                                                감상평     별점  공감수
0         1                              죽음이 아닌 의미없는 삶을 두려워 하라    5.0    0
1         2                           규남이가 귀남이가 됐다가 추남이 되는 이야기    4.0    0
2         3  둘의 관계가 굉장해 엄청나~!\n사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 ...    3.5    0
3         4                규남아 그래서 무슨 사랑을 했냐고 묻잔아.... 대답해.....    3.0    0
4         5                   재미도 없고 말도 안되고 결말도, 스토리도 너무 뻔한 영화    1.5    0
...     ...                                                ...    ...  ...
2830   2850                           짧은 러닝타임과 함께 킬링타임할 수 있을지.   별점없음    2
2831   2851                                      기대감이 아주 높아용~!  보고싶어요    0
2832   2852  "현재의 선택이 틀리지 않았음을 증명하라."\n\n구교환 배우는 장난 아니네...ㅋ...    3.5    8
2833   2853  놀애잘앙,,, 돌위아가,,, 삼진아웃반,,,\n외,엇덯해 이재훈과 구갼을 꼬셨슴니까,,,  보고싶어요    0
2834   2854                                        구교환은 추격 장인.    3.5    0

[2835 rows x 4 columns]

## **텍스트 전처리**
1. 리뷰에서 영어표현, puncation, 이모티콘은 모두 제거한다. (=한글 표현만 남긴다)

2. 띄어쓰기 변환기를 통해 띄어쓰기가 되어있지 않은 문장들을 제대로 변환한다.

3. 형태소 분석기를 통해 각각의 리뷰를 형태소 단위로 분리한다.

4. 한글자로 되어있는 것 제거

5. 빈도수가 많은 순으로 정렬 후 의미없는 단어(불용어) 제거

6. 최소빈도수 이하의 것들은 제거한다.

7. 잘못 분리 된 의미있는 단어들을 찾아서 사용자 단어 사전에 추가 (ex. 디테일 => 디 + 테일로 분리됨)

**한글표현만 남기기**
- 영어, 특수기호 제거

In [ ]:
def extract_word(text):
    hangul = re.compile('[^가-힣]')
    result = hangul.sub(' ', text)
    return result

In [ ]:
print("Before Extraction : ",reviews['감상평'][832])
print("After Extraction : ", extract_word(reviews['감상평'][832]))

print("Before Extraction : ",reviews['감상평'][283])
print("After Extraction : ", extract_word(reviews['감상평'][283]))

Before Extraction :  다시는 양화대교를 듣지 못할 것 같다
After Extraction :  다시는 양화대교를 듣지 못할 것 같다
Before Extraction :  기대를 안해서 그런지 쇼츠로 뜬 짧막한 장면들이 인상적이어서 인지 생각보다 괜찮았다. 이솜, 송강을 투입하며 억지스러운 개연성 없는 부분만 빠졌더라면..
After Extraction :  기대를 안해서 그런지 쇼츠로 뜬 짧막한 장면들이 인상적이어서 인지 생각보다 괜찮았다  이솜  송강을 투입하며 억지스러운 개연성 없는 부분만 빠졌더라면

In [ ]:
reviews['감상평'] = reviews['감상평'].apply(lambda x:extract_word(x))
reviews

      Index                                                감상평     별점  공감수
0         1                              죽음이 아닌 의미없는 삶을 두려워 하라    5.0    0
1         2                           규남이가 귀남이가 됐다가 추남이 되는 이야기    4.0    0
2         3  둘의 관계가 굉장해 엄청나   사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 극...    3.5    0
3         4                규남아 그래서 무슨 사랑을 했냐고 묻잔아     대답해         3.0    0
4         5                   재미도 없고 말도 안되고 결말도  스토리도 너무 뻔한 영화    1.5    0
...     ...                                                ...    ...  ...
2830   2850                           짧은 러닝타임과 함께 킬링타임할 수 있을지    별점없음    2
2831   2851                                      기대감이 아주 높아용    보고싶어요    0
2832   2852   현재의 선택이 틀리지 않았음을 증명하라    구교환 배우는 장난 아니네      ...    3.5    8
2833   2853   놀애잘앙    돌위아가    삼진아웃반    외 엇덯해 이재훈과 구갼을 꼬셨슴니까     보고싶어요    0
2834   2854                                        구교환은 추격 장인     3.5    0

[2835 rows x 4 columns]

**띄어쓰기 고치기**
- pykospacing 사용
- 전체 데이터에 사용시 시간 많이 소요됨...

In [ ]:
spacing = Spacing()

print("Before Fixing : ",reviews['감상평'][23])
print("After Fixing : ", spacing(reviews['감상평'][23]))
print("Before Fixing : ",reviews['감상평'][285])
print("After Fixing : ", spacing(reviews['감상평'][285]))

Before Fixing :  두 배우의 연기차력쇼덕에 좀 나았어요
After Fixing :  두 배우의 연기 차력쇼덕에 좀 나았어요
Before Fixing :  이제훈의 능구렁이같은 연기가 빛을 발한것같고 구교환과의 새로운조합도 괜찮다  처참하게만 묘사되는 북한과는 사뭇다르게 평범하면서도 고위 간부들은 유복한 생활을하는 북한군대가 묘사되는데 어색하면서도 새롭다는 느낌을 받았다  한편으론 북한사람들이 이영화를 모두봤으면 하는 생각이들정도로 이제훈의 탈북자의대한 집념을 보길 바라기도 했다  지뢰를 매일매일 피해가며 총을맞아가면서도 남한에서 살고싶다는 의지 혹은 사람답게 살아가고싶다는 의지가 화면을 뚫고 나왔다  그에비해 구교환 캐릭터는 아군도 아니고 적군도 아니고 애매한 위치인데 응원해주기에는 뭔가 거부감이 드는 캐릭터이기도하다  구교환이 이제훈을 잡으러갈때 컴퓨터처럼 전술을 짜는것보고 대단하기보다는 말도안된다는 생각이 지배했다  추격하는 장면에서 후반으로 갈수록 어려운상황은 컷편집으로 싹다 날려버리고 이야기를 쉽게 풀어가려고 하는건 꽤 아쉬운부분  이제훈과 구교환은 서로 배역이 바뀌었어도 색다른 재미를 줬을것 같기도하다
After Fixing :  이제훈의 능 구렁이 같은 연기가 빛을 발한 것 같고 구 교환과의 새로운 조합도 괜찮다 처참하게만 묘사되는 북한과는 사뭇 다르게 평범하면서도 고위 간부들은 유복한 생활을 하는 북한군대가 묘사되는데 어색하면서도 새롭다는 느낌을 받았다 한 편으론 북한 사람들이 이 영화를 모두 봤으면 하는 생각이 들 정도로 이제훈의 탈북자의 대한 집념을 보길 바라기도 했다 지뢰를 매일매일 피해가며  총을 맞아가면서도 남한에서 살고 싶다는 의 지 혹은 사람답게 살아가고 싶다는 의지가 화면을 뚫고 나왔다 그에 비해 구 교환 캐릭터는 아군도 아니고 적군도 아니고 애매한 위치인데 응원해주기에는 뭔가 거부감이 드는 캐릭터이기도 하다 구 교환이 이제훈을 잡으러 갈 때 컴퓨터처럼 전술을 짜는 것 보고 대단하기보다는 말도 안 된다는 생각이 지배했다 추격하는 장면에서 후반으로 갈수 록 어려운 상황은 컷 편집으로 싹 다 날려버리고 이야기를 쉽게 풀어가려고 하는 건 꽤 아쉬운 부분 이제훈과 구 교환은 서로 배역이 바뀌었어도 색다른 재미를 줬을 것 같기도 하다

In [ ]:
reviews['감상평'] = reviews['감상평'].apply(lambda x: spacing(x))
reviews

      Index                                                감상평     별점  공감수
0         1                             죽음이 아닌 의미 없는 삶을 두려워 하라    5.0    0
1         2                           규남이가 귀남이가 됐다가 추남이 되는 이야기    4.0    0
2         3  둘의 관계가 굉장해 엄청나 사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 극장에...    3.5    0
3         4                        규남아 그래서 무슨 사랑을 했냐고 묻잔 아 대답해    3.0    0
4         5                   재미도 없고 말도 안 되고 결말도 스토리도 너무 뻔한 영화    1.5    0
...     ...                                                ...    ...  ...
2830   2850                          짧은 러닝 타임과 함께 킬링 타임할 수 있을지   별점없음    2
2831   2851                                        기대감이 아주 높아용  보고싶어요    0
2832   2852  현재의 선택이 틀리지 않았음을 증명하라 구 교환 배우는 장난 아니네 그리고 감독님 ...    3.5    8
2833   2853             놀애 잘앙 돌위아가 삼진아웃 반 외 엇덯해 이재훈과 구갼을 꼬셨슴니까  보고싶어요    0
2834   2854                                        구 교환은 추격 장인    3.5    0

[2835 rows x 4 columns]

**형태소 분석**
- Okt 사용
- mecab 사용 가능(추후 추가)

In [ ]:
okt = Okt()
words = " ".join(reviews['감상평'].tolist())
words = okt.morphs(words,stem=True)

In [ ]:
#여러 리뷰들을 하나의 리스트 원소로 합쳐서 형태소를 분리한 뒤 Counter 객체로 빈도수 확인 예정
words

['죽음',
 '이',
 '아니다',
 '의미',
 '없다',
 '삶',
 '을',
 '두렵다',
 '하라',
 '규',
 '남다',
 '귀',
 '남',
 '이',
 '가',
 '돼다',
 '추남',
 '이',
 '되다',
 '이야기',
 '둘',
 '의',
 '관계',
 '가',
 '굉장하다',
 '엄청나다',
 '사운드',
 '가',
 '아주',
 '풍부하다',
 '영화',
 '라',
 '몰입',
 '감',
 '이',
 '좋다',
 '때문',
 '에',
 '극장',
 '에서',
 '보다',
 '하다',
 '영화',
 '중',
 '에',
 '하나',
 '다',
 '규',
 '남아',
 '그래서',
 '무슨',
 '사랑',
 '을',
 '하다',
 '묻다',
 '아',
 '대답',
 '하다',
 '재미',
 '도',
 '없다',
 '말',
 '도',
 '안',
 '되다',
 '결말',
 '도',
 '스토리',
 '도',
 '너무',
 '뻔하다',
 '영화',
 '구',
 '교환',
 '의',
 '매력',
 '속',
 '으로',
 '풍덩',
 '규남',
 '의',
 '뒤',
 '돌아보다',
 '않다',
 '내',
 '달리기',
 '를',
 '보다',
 '내',
 '마음',
 '속',
 '무언가',
 '가',
 '건드리다',
 '선우',
 '민',
 '어디서',
 '뭐',
 '하다',
 '영화',
 '가',
 '지뢰',
 '밭',
 '을',
 '다',
 '밟다',
 '다니다',
 '이',
 '정도',
 '면',
 '북한',
 '도',
 '자유',
 '국가',
 '아니다',
 '죽음',
 '이',
 '아니다',
 '의미',
 '없다',
 '삶',
 '을',
 '두렵다',
 '지나치다',
 '비현실적',
 '이라',
 '오히려',
 '웃기다',
 '두',
 '배우',
 '의',
 '눈빛',
 '피아노',
 '형',
 '과',
 '아문센',
 '으로',
 '완성',
 '꼽',
 '담당',
 '송강',
 '물리',
 '적',
 '탈주',
 '만이',
 '아니다',
 '꿈',
 '을',
 '가로',
 '막다',
 '환경',
 '으로부터',
 '탈주',
 '하다',
 '체념',
 '과',
 '희망',
 '오타쿠',
 '라면',
 '꼭',
 '보다',
 '걍',
 '혼자',
 '가다',
 '사궈',
 '고난',
 '중',
 '잠깐',
 '의',
 '휴식',
 '그',
 '이상',
 '도',
 '그',
 '이',
 '하다',
 '아니다',
 '배우',
 '들',
 '이',
 '연기',
 '로',
 '끌',
 '고',
 '가다',
 '영화',
 '배역',
 '의',
 '관계성',
 '은',
 '좋다',
 '극',
 '의',
 '흐름',
 '등',
 '연출',
 '이',
 '아쉽다',
 '배우',
 '들',
 '연기',
 '양화대교',
 '끝',
 '긴박하다',
 '심장',
 '쫄리',
 '는',
 '그렇다',
 '맛',
 '에',
 '보다',
 '영화',
 '구',
 '교환',
 '얼굴',
 '보기',
 '위해',
 '행복하다',
 '우리',
 '아프다',
 '말고',
 '어설프다',
 '연출',
 '과',
 '부족하다',
 '개연',
 '성',
 '공감',
 '어렵다',
 '주인공',
 '들',
 '의',
 '서사',
 '와',
 '관계',
 '설정',
 '송강',
 '이솜',
 '등',
 '의',
 '의아',
 '한',
 '등장인물',
 '들',
 '몰입',
 '을',
 '방해',
 '하다',
 '배우',
 '들',
 '의',
 '어설프다',
 '북한',
 '사투리',
 '쌩뚱맞',
 '은',
 '양화대교',
 '관객',
 '탈주',
 '유발',
 '영화',
 '두',
 '배우',
 '의',
 '연기',
 '차력',
 '쇼덕',
 '에',
 '좀',
 '나다',
 '볼',
 '만',
 '하다',
 '쫓다',
 '쫓기다',
 '추',
 '격전',
 '에',
 '심장',
 '이',
 '쫄',
 '깃쫄깃',
 '하다',
 '가다',
 '북한',
 '은',
 '일본',
 '과',
 '미국',
 '같다',
 '우리',
 '의',
 '공통',
 '되다',
 '적',
 '들',
 '을',
 '부수',
 '는',
 '데',
 '가담',
 '시키다',
 '적재적소',
 '로',
 '이용',
 '하다',
 '하다',
 '미개하다',
 '이렇다',
 '북한',
 '비다',
 '영화',
 '나',
 '만들다',
 '수준',
 '하고는',
 '큫',
 '남아',
 '너',
 '탈주',
 '햇',
 '서',
 '아니다',
 '그러니까',
 '왜',
 '들',
 '그렇게',
 '까지',
 '하다',
 '납득',
 '하다',
 '너무나',
 '많이',
 '비어',
 '있다',
 '서사',
 '들',
 '사투리',
 '가',
 '너무',
 '거슬리다',
 '집중',
 '이',
 '안',
 '되다',
 '연기',
 '는',
 '좋다',
 '중간',
 '중간',
 '못',
 '보다',
 '허구',
 '적',
 '요소',
 '가',
 '스토리',
 '가',
 '굉장하다',
 '열악하다',
 '영화',
 '배우',
 '들',
 '만',
 '빛',
 '바랬다',
 '탈북',
 '스토리',
 '질질',
 '끄다',
 '게',
 '예술',
 '임',
 '이',
 '것',
 '뭐예',
 '요',
 '실패',
 '를',
 '두렵다',
 '말',
 '자',
 '맥락',
 '연결',
 '이',
 '좀',
 '뜬금',
 '없다',
 '서사',
 '에서도',
 '쫄깃',
 '한',
 '긴장감',
 '을',
 '꾸준하다',
 '이',
 '끌다',
 '두',
 '배우',
 '의',
 '매력',
 '탈주',
 '조',
 '별',
 '과제',
 '에서',
 '구',
 '교환',
 '이',
 '멱',
 '살잡',
 '이',
 '조장',
 '인',
 '거지',
 '근데',
 '이제',
 '군인',
 '도',
 '북조선',
 '인도',
 '모두',
 '경력',
 '직인',
 '구',
 '교환',
 '과',
 '이제훈',
 '의',
 '연기',
 '가',
 '아깝다',
 '죽음',
 '보다',
 '의미',
 '없다',
 '삶',
 '을',
 '더',
 '두렵다',
 '사실',
 '거기',
 '서',
 '부터',
 '규남',
 '이의',
 '탈주',
 '는',
 '시작',
 '돼다',
 '거야',
 '뻔하다',
 '내용',
 '이',
 '예측',
 '이',
 '감',
 '허다',
 '나중',
 '에',
 '리',
 '현상',
 '이',
 '게이',
 '라는',
 '사실',
 '은',
 '충격',
 '으로',
 '다가오다',
 '분명',
 '영화',
 '내',
 '에서의',
 '빈',
 '틈',
 '은',
 '없다',
 '어째서',
 '알맹이',
 '가',
 '없다',
 '걸다',
 '두',
 '배우',
 '의',
 '연기력',
 '이',
 '멱살',
 '쥐',
 '고',
 '끌',
 '고',
 '가다',
 '느낌',
 '을',
 '지우다',
 '수가',
 '없다',
 '빽빽하다',
 '내용',
 '은',
 '좋다',
 '그러나',
 '뭘',
 '말',
 '하다',
 '하다',
 '이해',
 '하다',
 '수',
 '없다',
 '것',
 '또한',
 '사실',
 '늘어놓다',
 '내용',
 '은',
 '많다',
 '결말',
 '이',
 '너무',
 '아쉽다',
 '스토리',
 '적',
 '으로',
 '조금',
 '만',
 '더',
 '섬세하다',
 '좋다',
 '듯',
 '술래잡기',
 '가',
 '술래',
 '와',
 '도망자',
 '둘',
 '중',
 '하나',
 '라도',
 '없다',
 '완성',
 '되다',
 '않다',
 '희망',
 '하다',
 '이야기',
 '의',
 '흐름',
 '이',
 '다소',
 '아쉽다',
 '연출',
 '법',
 '이',
 '인상',
 '적',
 '자유',
 '에',
 '대해',
 '많다',
 '생각',
 '이',
 '들다',
 '의도',
 '치',
 '못',
 '한',
 '사랑',
 '의도',
 '하다',
 '도망',
 '영화',
 '의',
 '완성',
 '도',
 '는',
 '점',
 '하지만',
 '나르다',
 '울리다',
 '보너스',
 '점',
 '하다',
 '때',
 '내',
 '가',
 '간절하다',
 '살',
 '고',
 '싶다',
 '인생',
 '을',
 '현재',
 '형',
 '으로',
 '살',
 '고',
 '있다',
 '사람',
 '이',
 '있다',
 '난',
 '지금',
 '그렇다',
 '삶',
 '을',
 '살',
 '지다',
 '못',
 '하고',
 '이대로',
 '있다',
 '앞',
 '으로도',
 '그렇다',
 '수',
 '없다',
 '텐데',
 '내',
 '가',
 '이미',
 '오래전',
 '에',
 '잃어버리다',
 '소중하다',
 '것',
 '을',
 '당',
 '연스레',
 '지니',
 '고',
 '살다',
 '사람',
 '을',
 '마주',
 '칠',
 '때',
 '가',
 '있다',
 '내',
 '가',
 '영원하다',
 '여기',
 '멈추다',
 '서다',
 '있다',
 '말',
 '든',
 '누군가',
 '는',
 '내',
 '가',
 '포기',
 '한',
 '길',
 '을',
 '계속',
 '걸다',
 '나가다',
 '야',
 '말',
 '것',
 '이라는',
 '사실',
 '을',
 '직감',
 '하다',
 '되다',
 '순간',
 '이',
 '있다',
 '그때',
 '나',
 '는',
 '그',
 '누군가',
 '를',
 '진심',
 '으로',
 '응원',
 '하다',
 '수',
 '있다',
 '하지만',
 '어떻다',
 '마음',
 '은',
 '감히',
 '망치다',
 '해도',
 '망치다',
 '않다',
 '가라',
 '그리고',
 '허밍',
 '선상',
 '의',
 '아리아',
 '돌아서다',
 '걸음걸이',
 '가',
 '어째선',
 '지',
 '상쾌하다',
 '보',
 '여서',
 '나',
 '는',
 '그걸',
 '받아들이다',
 '수가',
 '없다',
 '영화',
 '를',
 '네',
 '번',
 '보다',
 '임규',
 '남',
 '이',
 '되다',
 '못',
 '하다',
 '리',
 '현상',
 '이라도',
 '되다',
 '싶다',
 '허우적대다',
 '있다',
 '우리',
 '모두',
 '와',
 '함께',
 '보고',
 '싶다',
 '영화',
 '진짜',
 '튀다',
 '싶다',
 '배우',
 '들',
 '의',
 '열연',
 '으로',
 '눈물',
 '이',
 '나다',
 '우직하다',
 '앞',
 '만',
 '보고',
 '달다',
 '하다',
 '탈주',
 '상황',
 '에',
 '계속',
 '하다',
 '주변',
 '을',
 '둘러보다',
 '멍청하다',
 '고증',
 '따윈',
 '버리다',
 '클리셰',
 '범벅',
 '자료',
 '조사',
 '는',
 '하다',
 '싶다',
 '정도',
 '로',
 '조악하다',
 '감성',
 '을',
 '강요',
 '한',
 '다',
 '너무',
 '어렵다',
 '길',
 '을',
 '꼬아놓',
 '고',
 '선',
 '직진',
 '하다',
 '하다',
 '무모하다',
 '구',
 '교환',
 '맛있다',
 '매력',
 '있다',
 '캐릭터',
 '도',
 '엉',
 '성하다',
 '서사',
 '안',
 '에서는',
 '가라앉다',
 '걸',
 '깨닫다',
 '해주다',
 '작품',
 '내',
 '가',
 '현실',
 '에',
 '순응',
 '하다',
 '삶',
 '을',
 '살',
 '고',
 '있다',
 '때문',
 '에',
 '영화',
 '를',
 '다',
 '보고',
 '뭔가',
 '가',
 '들다',
 '끓다',
 '다시',
 '또',
 '보다',
 '내',
 '갈다',
 '길',
 '내',
 '가',
 '정',
 '하다',
 '죽다',
 '내',
 '가',
 '죽다',
 '살다',
 '내',
 '가',
 '사다',
 '실패하다',
 '가다',
 '라는',
 '대사',
 '가',
 '나르다',
 '울컥',
 '하다',
 '하다',
 '쉣',
 '영화',
 '적',
 '허용',
 '남발',
 '에',
 '옆',
 '에서는',
 '와이프',
 '의',
 '넘어오다',
 '기',
 '초',
 '수급',
 '자',
 '타령',
 '에',
 '집중',
 '이',
 '어렵다',
 '그냥',
 '곱',
 '게',
 '보내다',
 '탈주',
 '의',
 '이유',
 '에도',
 '집중',
 '하다',
 '더',
 '공감',
 '이',
 '가다',
 '이야기',
 '개',
 '재밌다',
 '임규',
 '남',
 '개멋',
 '잇다',
 '너무',
 '너무',
 '재밌다',
 '이상하다',
 '데',
 '가',
 '하나',
 '도',
 '없다',
 '자다',
 '만들다',
 '엇',
 '늘다',
 '데',
 '이',
 '아니다',
 '이해',
 '되다',
 '않다',
 '서사',
 '이북',
 '쳥년드릐',
 '짜맀탼',
 '턀뷱대',
 '쇼둉',
 '가끔',
 '그렇다',
 '작품',
 '이',
 '있다',
 '주인공',
 '보다',
 '대립',
 '에',
 '있다',
 '상대편',
 '을',
 '더',
 '응원',
 '하다',
 '되다',
 '그',
 '의',
 '서사',
 '에',
 '더',
 '설득',
 '되다',
 '배경',
 '설명',
 '하나',
 '도',
 '없이',
 '모든',
 '이야기',
 '가',
 '전개',
 '되다',
 '킬링타임',
 '용',
 '으로',
 '적당하다',
 '뻔하다',
 '마음',
 '하다',
 '구석',
 '은',
 '울림',
 '나',
 '는',
 '무엇',
 '을',
 '저렇게',
 '갈망',
 '한',
 '적',
 '이',
 '있다',
 '가다',
 '영화',
 '소개',
 '프로그램',
 '내용',
 '이',
 '다',
 '이다',
 '이솔',
 '은',
 '왜',
 '나오다',
 '기',
 '야',
 '행복하다',
 '내',
 '길',
 '을',
 '내',
 '가',
 '선택',
 '하다',
 ...]

**한글자, 불용어 제거**
- 한 글자인 것들은 주로 조사가 많았고 그렇지 않아도 대체로 의미없는 단어
- 필요한 단어 제외 가능

In [ ]:
remove_one_word = [x for x in words if len(x)>1]
# remove_one_word = [x for x in words if len(x)>1 or x=="닉"] <<와 같이 or x =='' 하여 한글자여도 냅둘 것 지정 가능

len(remove_one_word) #개수

41251

In [ ]:
#collections의 Counter객체를 이용하여 단어별 빈도를 확인
from collections import Counter
frequent = Counter(remove_one_word).most_common();frequent

[('하다', 2006),
 ('영화', 798),
 ('있다', 734),
 ('교환', 587),
 ('보다', 523),
 ('없다', 435),
 ('좋다', 420),
 ('되다', 404),
 ('탈주', 390),
 ('으로', 365),
 ('않다', 353),
 ('에서', 325),
 ('배우', 292),
 ('이제훈', 286),
 ('같다', 277),
 ('싶다', 253),
 ('아니다', 244),
 ('너무', 235),
 ('연기', 231),
 ('현상', 230),
 ('규남', 212),
 ('가다', 209),
 ('이다', 206),
 ('북한', 195),
 ('실패하다', 190),
 ('나오다', 188),
 ('생각', 185),
 ('자다', 182),
 ('하고', 177),
 ('연출', 163),
 ('그렇다', 160),
 ('양화대교', 155),
 ('서사', 154),
 ('장면', 147),
 ('만들다', 146),
 ('실패', 145),
 ('아쉽다', 141),
 ('캐릭터', 140),
 ('자유', 135),
 ('까지', 133),
 ('송강', 131),
 ('재밌다', 122),
 ('들다', 120),
 ('감독', 114),
 ('이야기', 113),
 ('느낌', 111),
 ('남다', 110),
 ('사랑', 109),
 ('사람', 109),
 ('피아노', 106),
 ('개연', 105),
 ('많다', 103),
 ('진짜', 102),
 ('스토리', 100),
 ('두렵다', 98),
 ('모르다', 98),
 ('정도', 92),
 ('그냥', 92),
 ('그리고', 91),
 ('주다', 89),
 ('전개', 85),
 ('대한', 85),
 ('위해', 84),
 ('인물', 84),
 ('주인공', 83),
 ('긴장감', 83),
 ('부분', 83),
 ('하나', 82),
 ('몰입', 80),
 ('탈북', 78),
 ('보고', 78),
 ('에게', 78),
 ('선택', 76),
 ('버리다', 75),
 ('이렇다', 73),
 ('라는', 73),
 ('어떻다', 73),
 ('지다', 72),
 ('매력', 71),
 ('없이', 70),
 ('의미', 69),
 ('중간', 69),
 ('마음껏', 69),
 ('보이다', 69),
 ('하지만', 68),
 ('남한', 68),
 ('처럼', 68),
 ('현실', 67),
 ('계속', 66),
 ('보여주다', 65),
 ('때문', 64),
 ('뻔하다', 64),
 ('죽음', 63),
 ('희망', 63),
 ('행복하다', 63),
 ('알다', 63),
 ('오다', 63),
 ('괜찮다', 62),
 ('넣다', 62),
 ('근데', 61),
 ('자신', 61),
 ('마지막', 60),
 ('질주', 60),
 ('조금', 59),
 ('메시지', 59),
 ('자이언티', 59),
 ('우리', 58),
 ('시간', 57),
 ('내용', 56),
 ('살다', 56),
 ('그래도', 56),
 ('부터', 55),
 ('서다', 55),
 ('작품', 54),
 ('모든', 54),
 ('많이', 53),
 ('소재', 53),
 ('마음', 52),
 ('부족하다', 52),
 ('죽다', 52),
 ('음악', 52),
 ('맞다', 52),
 ('되어다', 51),
 ('노래', 50),
 ('달리다', 50),
 ('인데', 50),
 ('그래서', 49),
 ('차다', 49),
 ('타임', 49),
 ('밉다', 48),
 ('느끼다', 48),
 ('해주다', 46),
 ('뛰다', 46),
 ('잘생기다', 46),
 ('이랑', 46),
 ('내다', 46),
 ('관객', 45),
 ('가지', 45),
 ('라고', 45),
 ('지뢰', 44),
 ('짧다', 44),
 ('추격', 44),
 ('얼굴', 43),
 ('이라는', 43),
 ('뭔가', 43),
 ('이유', 43),
 ('한국', 43),
 ('다른', 43),
 ('크다', 43),
 ('이나', 43),
 ('느껴지다', 43),
 ('재미', 42),
 ('다시', 42),
 ('러닝', 42),
 ('정말', 42),
 ('등장', 42),
 ('나다', 41),
 ('무엇', 41),
 ('돼다', 40),
 ('설정', 40),
 ('지금', 40),
 ('포기', 40),
 ('상황', 40),
 ('늘다', 40),
 ('짜다', 40),
 ('놓다', 40),
 ('아쉬움', 40),
 ('그저', 40),
 ('말고', 39),
 ('집중', 39),
 ('시작', 39),
 ('건지다', 39),
 ('모습', 39),
 ('에는', 38),
 ('넘다', 38),
 ('초반', 38),
 ('인지', 38),
 ('도전', 38),
 ('모두', 37),
 ('대사', 37),
 ('내내', 37),
 ('액션', 37),
 ('미치다', 37),
 ('빠르다', 37),
 ('후반', 37),
 ('그것', 37),
 ('무슨', 36),
 ('에도', 36),
 ('러시아', 36),
 ('잡다', 36),
 ('편집', 36),
 ('시키다', 35),
 ('메세지', 35),
 ('이렇게', 35),
 ('해보다', 35),
 ('충분하다', 35),
 ('지만', 34),
 ('가장', 34),
 ('달리', 34),
 ('받다', 34),
 ('결말', 33),
 ('끄다', 33),
 ('나가다', 33),
 ('영화관', 33),
 ('엔딩', 33),
 ('이라', 32),
 ('순간', 32),
 ('임규', 32),
 ('성하다', 32),
 ('끝나다', 32),
 ('좋아하다', 32),
 ('청년', 32),
 ('자체', 32),
 ('먹다', 32),
 ('총알', 32),
 ('인가', 32),
 ('도감', 32),
 ('쫓다', 31),
 ('군인', 31),
 ('사실', 31),
 ('달다', 31),
 ('클리셰', 31),
 ('운명', 31),
 ('치다', 31),
 ('사이', 31),
 ('설명', 30),
 ('기회', 30),
 ('장르', 30),
 ('탈출', 30),
 ('여러', 30),
 ('청춘', 30),
 ('그러나', 29),
 ('이해', 29),
 ('에서는', 29),
 ('쉬다', 29),
 ('두다', 29),
 ('허다', 28),
 ('텐데', 28),
 ('빼다', 28),
 ('담다', 28),
 ('쓰다', 28),
 ('대다', 28),
 ('살리다', 28),
 ('떨어지다', 28),
 ('빠지다', 28),
 ('조차', 28),
 ('관계', 27),
 ('보기', 27),
 ('이솜', 27),
 ('다소', 27),
 ('일이', 27),
 ('전체', 27),
 ('쏘다', 27),
 ('가지다', 27),
 ('남자', 27),
 ('재미있다', 27),
 ('주제', 27),
 ('찾다', 27),
 ('단순하다', 27),
 ('섹시하다', 27),
 ('특히', 27),
 ('완성', 26),
 ('긴박하다', 26),
 ('아프다', 26),
 ('얼마나', 26),
 ('대체', 26),
 ('이고', 26),
 ('요소', 25),
 ('라도', 25),
 ('인상', 25),
 ('누군가', 25),
 ('배경', 25),
 ('세상', 25),
 ('감정', 25),
 ('집착', 25),
 ('넘치다', 25),
 ('역할', 25),
 ('흐름', 24),
 ('퀴어', 24),
 ('나쁘다', 24),
 ('같이', 24),
 ('새롭다', 24),
 ('스럽다', 24),
 ('지루하다', 24),
 ('갑자기', 24),
 ('과거', 24),
 ('스타일', 24),
 ('걸다', 23),
 ('연기력', 23),
 ('현재', 23),
 ('킬링타임', 23),
 ('표현', 23),
 ('차라리', 23),
 ('멋지다', 23),
 ('과정', 23),
 ('동혁', 23),
 ('기대하다', 23),
 ('깔끔하다', 23),
 ('광고', 23),
 ('아주', 22),
 ('뜬금', 22),
 ('간절하다', 22),
 ('함께', 22),
 ('힘들다', 22),
 ('역시', 22),
 ('사회', 22),
 ('넘어가다', 22),
 ('전달', 22),
 ('성은', 22),
 ('각본', 22),
 ('제일', 22),
 ('결국', 22),
 ('처음', 22),
 ('증명', 22),
 ('용기', 22),
 ('예상', 22),
 ('사운드', 21),
 ('극장', 21),
 ('눈빛', 21),
 ('비다', 21),
 ('납득', 21),
 ('응원', 21),
 ('갈다', 21),
 ('허용', 21),
 ('니까', 21),
 ('궁금하다', 21),
 ('어울리다', 21),
 ('찍다', 21),
 ('목적', 21),
 ('사빈', 21),
 ('제훈', 21),
 ('문제', 21),
 ('이르다', 21),
 ('바라다', 21),
 ('만큼', 21),
 ('나름', 21),
 ('오히려', 20),
 ('어렵다', 20),
 ('아깝다', 20),
 ('제대로', 20),
 ('불필요하다', 20),
 ('얘기', 20),
 ('깊다', 20),
 ('맞추다', 20),
 ('말다', 20),
 ('드라마', 20),
 ('해내다', 20),
 ('시도', 20),
 ('한테', 20),
 ('달려가다', 20),
 ('살아가다', 20),
 ('굳이', 20),
 ('확실하다', 20),
 ('서스펜스', 20),
 ('믿다', 20),
 ('생기다', 20),
 ('개인', 20),
 ('남아', 19),
 ('아문센', 19),
 ('거야', 19),
 ('의도', 19),
 ('여기', 19),
 ('탐험가', 19),
 ('중요하다', 19),
 ('자꾸', 19),
 ('리현상', 19),
 ('밖에', 19),
 ('배우다', 19),
 ('중반', 19),
 ('필요', 19),
 ('보다는', 19),
 ('기억', 19),
 ('다만', 19),
 ('틀리다', 19),
 ('이상', 18),
 ('에서도', 18),
 ('이제', 18),
 ('에서의', 18),
 ('또한', 18),
 ('해도', 18),
 ('플롯', 18),
 ('마다', 18),
 ('기대', 18),
 ('기도', 18),
 ('절대', 18),
 ('시나리오', 18),
 ('어느', 18),
 ('꿈꾸다', 18),
 ('남쪽', 18),
 ('의식', 18),
 ('길다', 18),
 ('멋있다', 18),
 ('목숨', 18),
 ('이란', 18),
 ('주연', 18),
 ('어설프다', 17),
 ('그렇게', 17),
 ('거지', 17),
 ('게이', 17),
 ('분명', 17),
 ('인생', 17),
 ('눈물', 17),
 ('설득', 17),
 ('불구', 17),
 ('얻다', 17),
 ('계획', 17),
 ('그게', 17),
 ('제목', 17),
 ('대한민국', 17),
 ('영상', 17),
 ('에겐', 17),
 ('미래', 17),
 ('인간', 17),
 ('위기', 17),
 ('풀다', 17),
 ('전반', 17),
 ('신파', 17),
 ('나아가다', 17),
 ('다르다', 17),
 ('뜨다', 17),
 ('잃다', 17),
 ('이라고', 17),
 ('따다', 17),
 ('진행', 17),
 ('밟다', 16),
 ('순응', 16),
 ('아무', 16),
 ('나라', 16),
 ('누구', 16),
 ('써다', 16),
 ('기다', 16),
 ('어디', 16),
 ('덕분', 16),
 ('이건', 16),
 ('다행', 16),
 ('별로', 16),
 ('택시', 16),
 ('성공', 16),
 ('섹시', 16),
 ('원하다', 16),
 ('벗어나다', 16),
 ('꾸다', 16),
 ('자기', 16),
 ('주어지다', 16),
 ('오랜', 16),
 ('의문', 16),
 ('통해', 16),
 ('단점', 16),
 ('놓치다', 16),
 ('세다', 16),
 ('따르다', 16),
 ('능력', 16),
 ('달리기', 15),
 ('라면', 15),
 ('공감', 15),
 ('격전', 15),
 ('수준', 15),
 ('수가', 15),
 ('열연', 15),
 ('보내다', 15),
 ('잇다', 15),
 ('웃음', 15),
 ('호흡', 15),
 ('일단', 15),
 ('박진', 15),
 ('거임', 15),
 ('되게', 15),
 ('이후', 15),
 ('리듬', 15),
 ('빈약하다', 15),
 ('가볍다', 15),
 ('불다', 15),
 ('긴장', 15),
 ('수도', 15),
 ('출연', 15),
 ('애매하다', 15),
 ('지도', 15),
 ('행복', 15),
 ('뮤비', 15),
 ('행동', 15),
 ('솔직하다', 15),
 ('만이', 14),
 ('끌다', 14),
 ('가라', 14),
 ('맛있다', 14),
 ('적당하다', 14),
 ('깔다', 14),
 ('열심히', 14),
 ('가능하다', 14),
 ('몇몇', 14),
 ('마무리', 14),
 ('이든', 14),
 ('체제', 14),
 ('촬영', 14),
 ('흥미롭다', 14),
 ('판타지', 14),
 ('상상', 14),
 ('심하다', 14),
 ('명확하다', 14),
 ('실제', 14),
 ('스스로', 14),
 ('깊이', 14),
 ('장점', 14),
 ('이종필', 14),
 ('들이다', 14),
 ('닿다', 14),
 ('돌아가다', 14),
 ('정신', 14),
 ('고민', 14),
 ('웃기다', 13),
 ('거기', 13),
 ('멈추다', 13),
 ('이라도', 13),
 ('갈망', 13),
 ('그리다', 13),
 ('그대로', 13),
 ('서로', 13),
 ('멀다', 13),
 ('높다', 13),
 ('한데', 13),
 ('성도', 13),
 ('귀순', 13),
 ('여성', 13),
 ('활용', 13),
 ('연속', 13),
 ('한국영', 13),
 ('묘사', 13),
 ('만나다', 13),
 ('어리다', 13),
 ('으로는', 13),
 ('채우다', 13),
 ('실력', 13),
 ('흐르다', 13),
 ('관람', 13),
 ('병사', 13),
 ('사격', 13),
 ('만으로', 13),
 ('공익', 13),
 ('전하', 13),
 ('고생', 13),
 ('긴박', 13),
 ('구도', 13),
 ('낙원', 13),
 ('굉장하다', 12),
 ('다니다', 12),
 ('비현실적', 12),
 ('막다', 12),
 ('심장', 12),
 ('생각나다', 12),
 ('성과', 12),
 ('코드', 12),
 ('이재훈', 12),
 ('의지', 12),
 ('개봉', 12),
 ('유랑민', 12),
 ('동무', 12),
 ('아버지', 12),
 ('케미', 12),
 ('마치', 12),
 ('극적', 12),
 ('전혀', 12),
 ('한다는', 12),
 ('이야', 12),
 ('스릴', 12),
 ('필요하다', 12),
 ('잡고', 12),
 ('오락', 12),
 ('앞길', 12),
 ('군대', 12),
 ('존재', 12),
 ('감동', 12),
 ('다루다', 12),
 ('갈등', 12),
 ('즐겁다', 12),
 ('오늘', 12),
 ('갈수록', 12),
 ('분명하다', 12),
 ('환불', 12),
 ('죽이다', 12),
 ('잊다', 12),
 ('분위기', 12),
 ('그나마', 12),
 ('제발', 12),
 ('캐스팅', 12),
 ('소좌', 12),
 ('오프닝', 12),
 ('담기다', 12),
 ('사용', 12),
 ('롯데', 12),
 ('듣다', 12),
 ('특별출연', 12),
 ('대신', 12),
 ('무리', 12),
 ('감각', 12),
 ('가족', 12),
 ('상업', 12),
 ('무언가', 11),
 ('국가', 11),
 ('잃어버리다', 11),
 ('받아들이다', 11),
 ('감성', 11),
 ('이상하다', 11),
 ('으로의', 11),
 ('진부하다', 11),
 ('신선하다', 11),
 ('더욱', 11),
 ('전형', 11),
 ('종필', 11),
 ('바로', 11),
 ('매우', 11),
 ('하니', 11),
 ('소리', 11),
 ('서울숲', 11),
 ('부여', 11),
 ('훌륭하다', 11),
 ('모로', 11),
 ('과의', 11),
 ('기분', 11),
 ('에선', 11),
 ('에만', 11),
 ('아름답다', 11),
 ('작위', 11),
 ('이번', 11),
 ('최고', 11),
 ('터지다', 11),
 ('시퀀스', 11),
 ('개다', 11),
 ('세련되다', 11),
 ('선물', 11),
 ('엄마', 11),
 ('희망이', 11),
 ('방향', 11),
 ('나비', 11),
 ('감상', 11),
 ('시네마', 11),
 ('직접', 11),
 ('달파란', 11),
 ('떠오르다', 11),
 ('하라', 10),
 ('너무나', 10),
 ('이미', 10),
 ('소중하다', 10),
 ('그때', 10),
 ('진심', 10),
 ('시대', 10),
 ('추천', 10),
 ('크게', 10),
 ('가치', 10),
 ('갖다', 10),
 ('이어지다', 10),
 ('보이', 10),
 ('쫄깃하', 10),
 ('까지는', 10),
 ('타다', 10),
 ('버전', 10),
 ('피하', 10),
 ('일어나다', 10),
 ('깨다', 10),
 ('떡밥', 10),
 ('물론', 10),
 ('방식', 10),
 ('이지', 10),
 ('이기', 10),
 ('이어서', 10),
 ('으론', 10),
 ('화면', 10),
 ('작다', 10),
 ('동생', 10),
 ('실소', 10),
 ('라서', 10),
 ('요즘', 10),
 ('복잡하다', 10),
 ('입다', 10),
 ('다가', 10),
 ('가득하다', 10),
 ('각자', 10),
 ('영화로', 10),
 ('삼진', 10),
 ('그룹', 10),
 ('맘껏', 10),
 ('모범', 10),
 ('처절하다', 10),
 ('박다', 10),
 ('강렬하다', 10),
 ('약간', 10),
 ('자의', 10),
 ('창업', 10),
 ('성의', 10),
 ('대로', 10),
 ('떠나다', 10),
 ('옳다', 10),
 ('편의', 10),
 ('바꾸다', 10),
 ('로서', 10),
 ('대충', 10),
 ('버프', 10),
 ('우연', 10),
 ('상당하다', 10),
 ('사라지다', 10),
 ('디테', 10),
 ('성공하다', 10),
 ('돌아보다', 9),
 ('선우', 9),
 ('쫓기다', 9),
 ('쫄깃', 9),
 ('섬세하다', 9),
 ('대해', 9),
 ('도망', 9),
 ('으로도', 9),
 ('잡히다', 9),
 ('상태', 9),
 ('점수', 9),
 ('흥미진진', 9),
 ('감사하다', 9),
 ('태어나다', 9),
 ('아이디어', 9),
 ('바라보다', 9),
 ('로맨스', 9),
 ('라디오', 9),
 ('충실하다', 9),
 ('다음', 9),
 ('유튜브', 9),
 ('밀다', 9),
 ('자유롭다', 9),
 ('부족', 9),
 ('사건', 9),
 ('살아나다', 9),
 ('적다', 9),
 ('에게는', 9),
 ('쾌감', 9),
 ('브로맨스', 9),
 ('어색하다', 9),
 ('간다', 9),
 ('동안', 9),
 ('집념', 9),
 ('그런데', 9),
 ('경계', 9),
 ('따라가다', 9),
 ('스타', 9),
 ('품다', 9),
 ('일지', 9),
 ('마저', 9),
 ('안타깝다', 9),
 ('들어가다', 9),
 ('카메라', 9),
 ('가깝다', 9),
 ('쓸다', 9),
 ('그만', 9),
 ('여운', 9),
 ('듯이', 9),
 ('딱하다', 9),
 ('이름', 9),
 ('메가박스', 9),
 ('개새끼', 9),
 ('군복', 9),
 ('에게도', 9),
 ('살짝', 9),
 ('만을', 9),
 ('보위부', 9),
 ('무섭다', 9),
 ('추적', 9),
 ('희다', 9),
 ('비주', 9),
 ('곁가지', 9),
 ('동기', 9),
 ('구성', 9),
 ('어쩌면', 9),
 ('남기다', 9),
 ('오로지', 9),
 ('장교', 9),
 ('주병', 9),
 ('나타나다', 9),
 ('머리', 9),
 ('늘어지다', 9),
 ('여전하다', 9),
 ('따로', 9),
 ('챙기다', 9),
 ('제작', 9),
 ('카메오', 9),
 ('엄청나다', 8),
 ('배역', 8),
 ('관계성', 8),
 ('방해', 8),
 ('울리다', 8),
 ('망치다', 8),
 ('여서', 8),
 ('그걸', 8),
 ('범벅', 8),
 ('가끔', 8),
 ('대립', 8),
 ('저렇게', 8),
 ('웃다', 8),
 ('내면', 8),
 ('치고', 8),
 ('도망치다', 8),
 ('이지만', 8),
 ('몰다', 8),
 ('극복', 8),
 ('언제', 8),
 ('보지', 8),
 ('감다', 8),
 ('반갑다', 8),
 ('마냥', 8),
 ('간의', 8),
 ('그치다', 8),
 ('드라이버', 8),
 ('악역', 8),
 ('동시', 8),
 ('노력', 8),
 ('안주', 8),
 ('겪다', 8),
 ('기대다', 8),
 ('어떻', 8),
 ('끊임없다', 8),
 ('원래', 8),
 ('경험', 8),
 ('인민', 8),
 ('지옥', 8),
 ('비슷하다', 8),
 ('올리다', 8),
 ('아무리', 8),
 ('전력', 8),
 ('치밀하다', 8),
 ('조합', 8),
 ('피해', 8),
 ('심다', 8),
 ('국뽕', 8),
 ('흘러가다', 8),
 ('막히다', 8),
 ('내일', 8),
 ('디테일', 8),
 ('한계', 8),
 ('차이', 8),
 ('훨씬', 8),
 ('적절하다', 8),
 ('도달', 8),
 ('보단', 8),
 ('사족', 8),
 ('깨지다', 8),
 ('울다', 8),
 ('군사분계선', 8),
 ('우민', 8),
 ('장치', 8),
 ('정해', 8),
 ('서브', 8),
 ('사연', 8),
 ('상이', 8),
 ('이루다', 8),
 ('거의', 8),
 ('바르다', 8),
 ('스릴러', 8),
 ('재미없다', 8),
 ('바람', 8),
 ('무대', 8),
 ('무난', 8),
 ('열망', 8),
 ('스럽게', 8),
 ('돌아오다', 8),
 ('던지다', 8),
 ('이기다', 8),
 ('읽다', 8),
 ('가득', 8),
 ('코미디', 8),
 ('인정', 8),
 ('완전하다', 8),
 ('표정', 8),
 ('자리', 8),
 ('부의', 8),
 ('지점', 8),
 ('예쁘다', 8),
 ('스콧', 8),
 ('대위', 8),
 ('환경', 7),
 ('혼자', 7),
 ('차력', 7),
 ('이의', 7),
 ('지우다', 7),
 ('돌아서다', 7),
 ('주변', 7),
 ('고증', 7),
 ('넘어오다', 7),
 ('당연하다', 7),
 ('삶다', 7),
 ('스푼', 7),
 ('정확하다', 7),
 ('평점', 7),
 ('총구', 7),
 ('부실하다', 7),
 ('들리다', 7),
 ('데리', 7),
 ('동성애', 7),
 ('년도', 7),
 ('그거', 7),
 ('만들어지다', 7),
 ('혹은', 7),
 ('미련', 7),
 ('전부', 7),
 ('취향', 7),
 ('억지스럽다', 7),
 ('목표', 7),
 ('뻗다', 7),
 ('음악캠프', 7),
 ('이를', 7),
 ('시절', 7),
 ('싫다', 7),
 ('도착', 7),
 ('정선', 7),
 ('시선', 7),
 ('가슴', 7),
 ('평이', 7),
 ('지원', 7),
 ('친구', 7),
 ('반복', 7),
 ('과는', 7),
 ('도대체', 7),
 ('위치', 7),
 ('이기도', 7),
 ('카리스마', 7),
 ('무비', 7),
 ('일리', 7),
 ('억지로', 7),
 ('혹시', 7),
 ('돌파', 7),
 ('만큼은', 7),
 ('조준', 7),
 ('어쨌든', 7),
 ('돋보이다', 7),
 ('음향', 7),
 ('고르다', 7),
 ('대화', 7),
 ('아문', 7),
 ('부대', 7),
 ('후임', 7),
 ('사적', 7),
 ('참신하다', 7),
 ('대출', 7),
 ('긍정', 7),
 ('유지', 7),
 ('막판', 7),
 ('제법', 7),
 ('분노', 7),
 ('만의', 7),
 ('개그', 7),
 ('완벽하다', 7),
 ('전이', 7),
 ('반전', 7),
 ('흘리다', 7),
 ('프로파간다', 7),
 ('여자', 7),
 ('모델', 7),
 ('드러나다', 7),
 ('인사', 7),
 ('뭐라다', 7),
 ('형편', 7),
 ('강하다', 7),
 ('상관', 7),
 ('선율', 7),
 ('신기하다', 7),
 ('팬픽', 7),
 ('억지', 7),
 ('동화', 7),
 ('중후', 7),
 ('이미지', 7),
 ('아마도', 7),
 ('당황', 7),
 ('쓰이다', 7),
 ('입장', 7),
 ('만년필', 7),
 ('다리', 7),
 ('맡다', 7),
 ('어찌', 7),
 ('흙탕물', 7),
 ('하나로', 7),
 ('정해진', 7),
 ('회수', 7),
 ('사탕', 7),
 ('지나치다', 6),
 ('으로부터', 6),
 ('오타쿠', 6),
 ('사투리', 6),
 ('거슬리다', 6),
 ('예술', 6),
 ('영원하다', 6),
 ('깨닫다', 6),
 ('점점', 6),
 ('끝내', 6),
 ('뿐이다', 6),
 ('클래식', 6),
 ('드리다', 6),
 ('우리나라', 6),
 ('따라오다', 6),
 ('애쓰다', 6),
 ('재밋', 6),
 ('선명하다', 6),
 ('기다리다', 6),
 ('몰입도', 6),
 ('떨어뜨리다', 6),
 ('망설이다', 6),
 ('유일하다', 6),
 ('아직', 6),
 ...]

In [ ]:
# stopwords(불용어) 파일 업로드
from google.colab import files
uploaded = files.upload()

Saving stopwords.txt to stopwords.txt

In [ ]:
with open('stopwords.txt', 'r', encoding='cp949') as f:
    list_file = f.readlines()
stopwords = list_file[0].split(",")
remove_stopwords = [x for x in remove_one_word if x not in stopwords]
len(remove_stopwords)
#불용어 제거 후

27834

In [ ]:
Counter(remove_stopwords).most_common()
#이전보다 의미있는 단어만 남음

[('교환', 587),
 ('좋다', 420),
 ('탈주', 390),
 ('배우', 292),
 ('이제훈', 286),
 ('연기', 231),
 ('현상', 230),
 ('규남', 212),
 ('북한', 195),
 ('실패하다', 190),
 ('생각', 185),
 ('자다', 182),
 ('연출', 163),
 ('양화대교', 155),
 ('서사', 154),
 ('장면', 147),
 ('만들다', 146),
 ('실패', 145),
 ('아쉽다', 141),
 ('캐릭터', 140),
 ('자유', 135),
 ('송강', 131),
 ('재밌다', 122),
 ('감독', 114),
 ('이야기', 113),
 ('느낌', 111),
 ('사랑', 109),
 ('사람', 109),
 ('피아노', 106),
 ('개연', 105),
 ('많다', 103),
 ('스토리', 100),
 ('두렵다', 98),
 ('전개', 85),
 ('인물', 84),
 ('주인공', 83),
 ('긴장감', 83),
 ('몰입', 80),
 ('탈북', 78),
 ('선택', 76),
 ('버리다', 75),
 ('지다', 72),
 ('매력', 71),
 ('의미', 69),
 ('중간', 69),
 ('마음껏', 69),
 ('남한', 68),
 ('현실', 67),
 ('보여주다', 65),
 ('뻔하다', 64),
 ('죽음', 63),
 ('희망', 63),
 ('행복하다', 63),
 ('괜찮다', 62),
 ('넣다', 62),
 ('마지막', 60),
 ('질주', 60),
 ('메시지', 59),
 ('자이언티', 59),
 ('내용', 56),
 ('살다', 56),
 ('서다', 55),
 ('작품', 54),
 ('소재', 53),
 ('마음', 52),
 ('부족하다', 52),
 ('죽다', 52),
 ('음악', 52),
 ('맞다', 52),
 ('노래', 50),
 ('달리다', 50),
 ('차다', 49),
 ('타임', 49),
 ('밉다', 48),
 ('느끼다', 48),
 ('해주다', 46),
 ('뛰다', 46),
 ('잘생기다', 46),
 ('관객', 45),
 ('지뢰', 44),
 ('짧다', 44),
 ('추격', 44),
 ('얼굴', 43),
 ('뭔가', 43),
 ('이유', 43),
 ('한국', 43),
 ('크다', 43),
 ('느껴지다', 43),
 ('재미', 42),
 ('러닝', 42),
 ('등장', 42),
 ('설정', 40),
 ('포기', 40),
 ('상황', 40),
 ('늘다', 40),
 ('짜다', 40),
 ('놓다', 40),
 ('아쉬움', 40),
 ('집중', 39),
 ('시작', 39),
 ('건지다', 39),
 ('초반', 38),
 ('인지', 38),
 ('도전', 38),
 ('대사', 37),
 ('액션', 37),
 ('미치다', 37),
 ('빠르다', 37),
 ('후반', 37),
 ('그것', 37),
 ('에도', 36),
 ('러시아', 36),
 ('잡다', 36),
 ('편집', 36),
 ('메세지', 35),
 ('해보다', 35),
 ('충분하다', 35),
 ('달리', 34),
 ('결말', 33),
 ('나가다', 33),
 ('영화관', 33),
 ('엔딩', 33),
 ('순간', 32),
 ('임규', 32),
 ('성하다', 32),
 ('끝나다', 32),
 ('좋아하다', 32),
 ('청년', 32),
 ('먹다', 32),
 ('총알', 32),
 ('도감', 32),
 ('쫓다', 31),
 ('군인', 31),
 ('사실', 31),
 ('달다', 31),
 ('클리셰', 31),
 ('운명', 31),
 ('치다', 31),
 ('사이', 31),
 ('설명', 30),
 ('기회', 30),
 ('장르', 30),
 ('탈출', 30),
 ('청춘', 30),
 ('이해', 29),
 ('에서는', 29),
 ('쉬다', 29),
 ('허다', 28),
 ('텐데', 28),
 ('빼다', 28),
 ('쓰다', 28),
 ('살리다', 28),
 ('떨어지다', 28),
 ('빠지다', 28),
 ('관계', 27),
 ('보기', 27),
 ('이솜', 27),
 ('전체', 27),
 ('쏘다', 27),
 ('남자', 27),
 ('재미있다', 27),
 ('주제', 27),
 ('찾다', 27),
 ('단순하다', 27),
 ('섹시하다', 27),
 ('완성', 26),
 ('긴박하다', 26),
 ('아프다', 26),
 ('대체', 26),
 ('요소', 25),
 ('라도', 25),
 ('인상', 25),
 ('누군가', 25),
 ('배경', 25),
 ('세상', 25),
 ('감정', 25),
 ('집착', 25),
 ('넘치다', 25),
 ('역할', 25),
 ('흐름', 24),
 ('퀴어', 24),
 ('나쁘다', 24),
 ('새롭다', 24),
 ('지루하다', 24),
 ('갑자기', 24),
 ('과거', 24),
 ('스타일', 24),
 ('걸다', 23),
 ('연기력', 23),
 ('현재', 23),
 ('킬링타임', 23),
 ('표현', 23),
 ('멋지다', 23),
 ('과정', 23),
 ('동혁', 23),
 ('기대하다', 23),
 ('깔끔하다', 23),
 ('광고', 23),
 ('아주', 22),
 ('뜬금', 22),
 ('간절하다', 22),
 ('힘들다', 22),
 ('사회', 22),
 ('넘어가다', 22),
 ('전달', 22),
 ('성은', 22),
 ('각본', 22),
 ('처음', 22),
 ('증명', 22),
 ('용기', 22),
 ('예상', 22),
 ('사운드', 21),
 ('극장', 21),
 ('눈빛', 21),
 ('비다', 21),
 ('납득', 21),
 ('응원', 21),
 ('갈다', 21),
 ('허용', 21),
 ('니까', 21),
 ('궁금하다', 21),
 ('어울리다', 21),
 ('찍다', 21),
 ('목적', 21),
 ('사빈', 21),
 ('제훈', 21),
 ('문제', 21),
 ('이르다', 21),
 ('바라다', 21),
 ('나름', 21),
 ('어렵다', 20),
 ('아깝다', 20),
 ('불필요하다', 20),
 ('얘기', 20),
 ('깊다', 20),
 ('맞추다', 20),
 ('말다', 20),
 ('드라마', 20),
 ('해내다', 20),
 ('시도', 20),
 ('달려가다', 20),
 ('살아가다', 20),
 ('굳이', 20),
 ('확실하다', 20),
 ('서스펜스', 20),
 ('믿다', 20),
 ('생기다', 20),
 ('남아', 19),
 ('아문센', 19),
 ('거야', 19),
 ('의도', 19),
 ('탐험가', 19),
 ('중요하다', 19),
 ('자꾸', 19),
 ('리현상', 19),
 ('배우다', 19),
 ('중반', 19),
 ('필요', 19),
 ('기억', 19),
 ('틀리다', 19),
 ('에서도', 18),
 ('에서의', 18),
 ('해도', 18),
 ('플롯', 18),
 ('기대', 18),
 ('기도', 18),
 ('절대', 18),
 ('시나리오', 18),
 ('꿈꾸다', 18),
 ('남쪽', 18),
 ('의식', 18),
 ('길다', 18),
 ('멋있다', 18),
 ('목숨', 18),
 ('주연', 18),
 ('어설프다', 17),
 ('거지', 17),
 ('게이', 17),
 ('분명', 17),
 ('인생', 17),
 ('눈물', 17),
 ('설득', 17),
 ('불구', 17),
 ('얻다', 17),
 ('계획', 17),
 ('그게', 17),
 ('제목', 17),
 ('대한민국', 17),
 ('영상', 17),
 ('에겐', 17),
 ('미래', 17),
 ('인간', 17),
 ('위기', 17),
 ('풀다', 17),
 ('전반', 17),
 ('신파', 17),
 ('나아가다', 17),
 ('다르다', 17),
 ('뜨다', 17),
 ('잃다', 17),
 ('따다', 17),
 ('진행', 17),
 ('밟다', 16),
 ('순응', 16),
 ('아무', 16),
 ('나라', 16),
 ('기다', 16),
 ('덕분', 16),
 ('다행', 16),
 ('별로', 16),
 ('택시', 16),
 ('성공', 16),
 ('섹시', 16),
 ('원하다', 16),
 ('벗어나다', 16),
 ('꾸다', 16),
 ('주어지다', 16),
 ('오랜', 16),
 ('의문', 16),
 ('통해', 16),
 ('단점', 16),
 ('놓치다', 16),
 ('세다', 16),
 ('따르다', 16),
 ('능력', 16),
 ('달리기', 15),
 ('라면', 15),
 ('공감', 15),
 ('격전', 15),
 ('수준', 15),
 ('수가', 15),
 ('열연', 15),
 ('보내다', 15),
 ('웃음', 15),
 ('호흡', 15),
 ('박진', 15),
 ('거임', 15),
 ('되게', 15),
 ('이후', 15),
 ('리듬', 15),
 ('빈약하다', 15),
 ('가볍다', 15),
 ('불다', 15),
 ('긴장', 15),
 ('수도', 15),
 ('출연', 15),
 ('애매하다', 15),
 ('지도', 15),
 ('행복', 15),
 ('뮤비', 15),
 ('행동', 15),
 ('솔직하다', 15),
 ('만이', 14),
 ('끌다', 14),
 ('가라', 14),
 ('맛있다', 14),
 ('적당하다', 14),
 ('깔다', 14),
 ('열심히', 14),
 ('가능하다', 14),
 ('몇몇', 14),
 ('마무리', 14),
 ('이든', 14),
 ('체제', 14),
 ('촬영', 14),
 ('흥미롭다', 14),
 ('판타지', 14),
 ('상상', 14),
 ('심하다', 14),
 ('명확하다', 14),
 ('실제', 14),
 ('스스로', 14),
 ('깊이', 14),
 ('장점', 14),
 ('이종필', 14),
 ('들이다', 14),
 ('닿다', 14),
 ('돌아가다', 14),
 ('정신', 14),
 ('고민', 14),
 ('웃기다', 13),
 ('거기', 13),
 ('멈추다', 13),
 ('이라도', 13),
 ('갈망', 13),
 ('그리다', 13),
 ('그대로', 13),
 ('서로', 13),
 ('멀다', 13),
 ('높다', 13),
 ('성도', 13),
 ('귀순', 13),
 ('여성', 13),
 ('활용', 13),
 ('연속', 13),
 ('한국영', 13),
 ('묘사', 13),
 ('만나다', 13),
 ('어리다', 13),
 ('채우다', 13),
 ('실력', 13),
 ('흐르다', 13),
 ('병사', 13),
 ('사격', 13),
 ('만으로', 13),
 ('공익', 13),
 ('전하', 13),
 ('고생', 13),
 ('긴박', 13),
 ('구도', 13),
 ('낙원', 13),
 ('굉장하다', 12),
 ('다니다', 12),
 ('비현실적', 12),
 ('막다', 12),
 ('심장', 12),
 ('생각나다', 12),
 ('성과', 12),
 ('코드', 12),
 ('이재훈', 12),
 ('의지', 12),
 ('개봉', 12),
 ('유랑민', 12),
 ('동무', 12),
 ('아버지', 12),
 ('케미', 12),
 ('극적', 12),
 ('스릴', 12),
 ('필요하다', 12),
 ('잡고', 12),
 ('오락', 12),
 ('앞길', 12),
 ('군대', 12),
 ('존재', 12),
 ('감동', 12),
 ('다루다', 12),
 ('갈등', 12),
 ('즐겁다', 12),
 ('갈수록', 12),
 ('분명하다', 12),
 ('환불', 12),
 ('죽이다', 12),
 ('잊다', 12),
 ('분위기', 12),
 ('그나마', 12),
 ('캐스팅', 12),
 ('소좌', 12),
 ('오프닝', 12),
 ('담기다', 12),
 ('사용', 12),
 ('롯데', 12),
 ('듣다', 12),
 ('특별출연', 12),
 ('대신', 12),
 ('무리', 12),
 ('감각', 12),
 ('가족', 12),
 ('상업', 12),
 ('무언가', 11),
 ('국가', 11),
 ('잃어버리다', 11),
 ('받아들이다', 11),
 ('감성', 11),
 ('이상하다', 11),
 ('으로의', 11),
 ('진부하다', 11),
 ('신선하다', 11),
 ('더욱', 11),
 ('전형', 11),
 ('종필', 11),
 ('하니', 11),
 ('소리', 11),
 ('서울숲', 11),
 ('부여', 11),
 ('훌륭하다', 11),
 ('모로', 11),
 ('과의', 11),
 ('기분', 11),
 ('에선', 11),
 ('에만', 11),
 ('아름답다', 11),
 ('작위', 11),
 ('최고', 11),
 ('터지다', 11),
 ('시퀀스', 11),
 ('개다', 11),
 ('세련되다', 11),
 ('선물', 11),
 ('엄마', 11),
 ('희망이', 11),
 ('방향', 11),
 ('나비', 11),
 ('감상', 11),
 ('시네마', 11),
 ('직접', 11),
 ('달파란', 11),
 ('떠오르다', 11),
 ('하라', 10),
 ('너무나', 10),
 ('이미', 10),
 ('소중하다', 10),
 ('진심', 10),
 ('시대', 10),
 ('추천', 10),
 ('크게', 10),
 ('가치', 10),
 ('갖다', 10),
 ('이어지다', 10),
 ('보이', 10),
 ('쫄깃하', 10),
 ('까지는', 10),
 ('버전', 10),
 ('피하', 10),
 ('일어나다', 10),
 ('깨다', 10),
 ('떡밥', 10),
 ('방식', 10),
 ('이지', 10),
 ('이기', 10),
 ('으론', 10),
 ('화면', 10),
 ('작다', 10),
 ('동생', 10),
 ('실소', 10),
 ('요즘', 10),
 ('복잡하다', 10),
 ('입다', 10),
 ('다가', 10),
 ('가득하다', 10),
 ('영화로', 10),
 ('삼진', 10),
 ('그룹', 10),
 ('맘껏', 10),
 ('모범', 10),
 ('처절하다', 10),
 ('박다', 10),
 ('강렬하다', 10),
 ('자의', 10),
 ('창업', 10),
 ('성의', 10),
 ('떠나다', 10),
 ('옳다', 10),
 ('편의', 10),
 ('바꾸다', 10),
 ('로서', 10),
 ('대충', 10),
 ('버프', 10),
 ('우연', 10),
 ('상당하다', 10),
 ('사라지다', 10),
 ('디테', 10),
 ('성공하다', 10),
 ('돌아보다', 9),
 ('선우', 9),
 ('쫓기다', 9),
 ('쫄깃', 9),
 ('섬세하다', 9),
 ('도망', 9),
 ('으로도', 9),
 ('잡히다', 9),
 ('상태', 9),
 ('점수', 9),
 ('흥미진진', 9),
 ('감사하다', 9),
 ('태어나다', 9),
 ('아이디어', 9),
 ('바라보다', 9),
 ('로맨스', 9),
 ('라디오', 9),
 ('충실하다', 9),
 ('유튜브', 9),
 ('밀다', 9),
 ('자유롭다', 9),
 ('부족', 9),
 ('사건', 9),
 ('살아나다', 9),
 ('적다', 9),
 ('쾌감', 9),
 ('브로맨스', 9),
 ('어색하다', 9),
 ('간다', 9),
 ('집념', 9),
 ('경계', 9),
 ('따라가다', 9),
 ('스타', 9),
 ('품다', 9),
 ('일지', 9),
 ('안타깝다', 9),
 ('들어가다', 9),
 ('카메라', 9),
 ('가깝다', 9),
 ('쓸다', 9),
 ('그만', 9),
 ('여운', 9),
 ('듯이', 9),
 ('딱하다', 9),
 ('이름', 9),
 ('메가박스', 9),
 ('개새끼', 9),
 ('군복', 9),
 ('에게도', 9),
 ('살짝', 9),
 ('만을', 9),
 ('보위부', 9),
 ('무섭다', 9),
 ('추적', 9),
 ('희다', 9),
 ('비주', 9),
 ('곁가지', 9),
 ('동기', 9),
 ('구성', 9),
 ('어쩌면', 9),
 ('남기다', 9),
 ('장교', 9),
 ('주병', 9),
 ('나타나다', 9),
 ('머리', 9),
 ('늘어지다', 9),
 ('여전하다', 9),
 ('따로', 9),
 ('챙기다', 9),
 ('제작', 9),
 ('카메오', 9),
 ('엄청나다', 8),
 ('배역', 8),
 ('관계성', 8),
 ('방해', 8),
 ('울리다', 8),
 ('망치다', 8),
 ('그걸', 8),
 ('범벅', 8),
 ('가끔', 8),
 ('대립', 8),
 ('저렇게', 8),
 ('웃다', 8),
 ('내면', 8),
 ('치고', 8),
 ('도망치다', 8),
 ('몰다', 8),
 ('극복', 8),
 ('보지', 8),
 ('감다', 8),
 ('반갑다', 8),
 ('마냥', 8),
 ('간의', 8),
 ('그치다', 8),
 ('드라이버', 8),
 ('악역', 8),
 ('동시', 8),
 ('노력', 8),
 ('안주', 8),
 ('겪다', 8),
 ('기대다', 8),
 ('어떻', 8),
 ('끊임없다', 8),
 ('경험', 8),
 ('인민', 8),
 ('지옥', 8),
 ('올리다', 8),
 ('아무리', 8),
 ('전력', 8),
 ('치밀하다', 8),
 ('조합', 8),
 ('피해', 8),
 ('심다', 8),
 ('국뽕', 8),
 ('흘러가다', 8),
 ('막히다', 8),
 ('내일', 8),
 ('디테일', 8),
 ('한계', 8),
 ('차이', 8),
 ('적절하다', 8),
 ('도달', 8),
 ('사족', 8),
 ('깨지다', 8),
 ('울다', 8),
 ('군사분계선', 8),
 ('우민', 8),
 ('장치', 8),
 ('정해', 8),
 ('서브', 8),
 ('사연', 8),
 ('상이', 8),
 ('이루다', 8),
 ('바르다', 8),
 ('스릴러', 8),
 ('재미없다', 8),
 ('바람', 8),
 ('무대', 8),
 ('무난', 8),
 ('열망', 8),
 ('스럽게', 8),
 ('돌아오다', 8),
 ('던지다', 8),
 ('이기다', 8),
 ('읽다', 8),
 ('가득', 8),
 ('코미디', 8),
 ('인정', 8),
 ('완전하다', 8),
 ('표정', 8),
 ('자리', 8),
 ('부의', 8),
 ('지점', 8),
 ('예쁘다', 8),
 ('스콧', 8),
 ('대위', 8),
 ('환경', 7),
 ('차력', 7),
 ('이의', 7),
 ('지우다', 7),
 ('돌아서다', 7),
 ('주변', 7),
 ('고증', 7),
 ('넘어오다', 7),
 ('당연하다', 7),
 ('삶다', 7),
 ('스푼', 7),
 ('정확하다', 7),
 ('평점', 7),
 ('총구', 7),
 ('부실하다', 7),
 ('들리다', 7),
 ('데리', 7),
 ('동성애', 7),
 ('년도', 7),
 ('그거', 7),
 ('만들어지다', 7),
 ('미련', 7),
 ('취향', 7),
 ('억지스럽다', 7),
 ('목표', 7),
 ('뻗다', 7),
 ('음악캠프', 7),
 ('이를', 7),
 ('시절', 7),
 ('싫다', 7),
 ('도착', 7),
 ('정선', 7),
 ('시선', 7),
 ('가슴', 7),
 ('평이', 7),
 ('지원', 7),
 ('친구', 7),
 ('반복', 7),
 ('과는', 7),
 ('도대체', 7),
 ('위치', 7),
 ('이기도', 7),
 ('카리스마', 7),
 ('무비', 7),
 ('일리', 7),
 ('억지로', 7),
 ('돌파', 7),
 ('만큼은', 7),
 ('조준', 7),
 ('어쨌든', 7),
 ('돋보이다', 7),
 ('음향', 7),
 ('고르다', 7),
 ('대화', 7),
 ('아문', 7),
 ('부대', 7),
 ('후임', 7),
 ('사적', 7),
 ('참신하다', 7),
 ('대출', 7),
 ('긍정', 7),
 ('유지', 7),
 ('막판', 7),
 ('제법', 7),
 ('분노', 7),
 ('만의', 7),
 ('개그', 7),
 ('완벽하다', 7),
 ('전이', 7),
 ('반전', 7),
 ('흘리다', 7),
 ('프로파간다', 7),
 ('여자', 7),
 ('모델', 7),
 ('드러나다', 7),
 ('인사', 7),
 ('뭐라다', 7),
 ('형편', 7),
 ('강하다', 7),
 ('상관', 7),
 ('선율', 7),
 ('신기하다', 7),
 ('팬픽', 7),
 ('억지', 7),
 ('동화', 7),
 ('중후', 7),
 ('이미지', 7),
 ('아마도', 7),
 ('당황', 7),
 ('쓰이다', 7),
 ('입장', 7),
 ('만년필', 7),
 ('다리', 7),
 ('맡다', 7),
 ('흙탕물', 7),
 ('하나로', 7),
 ('정해진', 7),
 ('회수', 7),
 ('사탕', 7),
 ('지나치다', 6),
 ('으로부터', 6),
 ('오타쿠', 6),
 ('사투리', 6),
 ('거슬리다', 6),
 ('예술', 6),
 ('영원하다', 6),
 ('깨닫다', 6),
 ('점점', 6),
 ('끝내', 6),
 ('클래식', 6),
 ('드리다', 6),
 ('우리나라', 6),
 ('따라오다', 6),
 ('애쓰다', 6),
 ('재밋', 6),
 ('선명하다', 6),
 ('기다리다', 6),
 ('몰입도', 6),
 ('떨어뜨리다', 6),
 ('망설이다', 6),
 ('유일하다', 6),
 ('빌드업', 6),
 ('약하다', 6),
 ('진지하다', 6),
 ('프리퀄', 6),
 ('붙이다', 6),
 ('소화', 6),
 ('칭찬', 6),
 ('도망가다', 6),
 ('해결', 6),
 ('만하', 6),
 ('독특하다', 6),
 ('만족하다', 6),
 ('배철수', 6),
 ('대결', 6),
 ('화보', 6),
 ('번째', 6),
 ('구멍', 6),
 ('도로', 6),
 ('연습', 6),
 ('좌절', 6),
 ('현대', 6),
 ('까진', 6),
 ('매일', 6),
 ('뚫다', 6),
 ('남북', 6),
 ('자꾸만', 6),
 ('조선', 6),
 ('부르다', 6),
 ('결과', 6),
 ('와중', 6),
 ('영화인', 6),
 ('재료', 6),
 ('깨우다', 6),
 ('파악', 6),
 ('에너지', 6),
 ('밀고', 6),
 ('평가', 6),
 ('대부분', 6),
 ('무시', 6),
 ('구조', 6),
 ('영어', 6),
 ('토익', 6),
 ('너머', 6),
 ('그러하다', 6),
 ('최선', 6),
 ('붙다', 6),
 ('찾기', 6),
 ('포인트', 6),
 ('더하다', 6),
 ('웃기', 6),
 ('인가요', 6),
 ('걱정', 6),
 ('뮤직비디오', 6),
 ('거나', 6),
 ('어머니', 6),
 ('반성', 6),
 ('보수', 6),
 ('낫다', 6),
 ('위로', 6),
 ('이자', 6),
 ('고자', 6),
 ('보이지', 6),
 ('후회', 6),
 ('틀다', 6),
 ('관련', 6),
 ('지나가다', 6),
 ('고백', 6),
 ('장난', 6),
 ('여지', 6),
 ('이데올로기', 6),
 ('키스', 6),
 ('행운', 6),
 ('집단', 6),
 ('쌓다', 6),
 ('강력하다', 6),
 ('초점', 6),
 ('앉다', 6),
 ('항상', 6),
 ('상미', 6),
 ('쉽다', 6),
 ('커버', 6),
 ('쥐다', 6),
 ('생일', 6),
 ('축하', 6),
 ('클라이맥스', 6),
 ('찾아보다', 6),
 ('전과', 6),
 ('내리다', 6),
 ('끊기다', 6),
 ('스러운', 6),
 ('겁니다', 6),
 ('밋밋하다', 6),
 ('립밤', 6),
 ('지휘', 6),
 ('와도', 6),
 ('라인', 6),
 ('스타일리시', 6),
 ('조금씩', 6),
 ('기지', 6),
 ('건가', 6),
 ('인하다', 6),
 ('탄탄하다', 6),
 ('수많다', 6),
 ('스치다', 6),
 ('드러내다', 6),
 ('유치하다', 6),
 ('새다', 6),
 ('느닷없다', 6),
 ('먼저', 6),
 ('군더더기', 6),
 ('스크린', 6),
 ('남극점', 6),
 ('어디서', 5),
 ('사궈', 5),
 ('의아', 5),
 ('등장인물', 5),
 ('이용', 5),
 ('질질', 5),
 ('맥락', 5),
 ('도망자', 5),
 ('튀다', 5),
 ('조악하다', 5),
 ('울림', 5),
 ('정리', 5),
 ('줄거리', 5),
 ('카타르', 5),
 ('시스', 5),
 ('피아니스트', 5),
 ('디피', 5),
 ('따뜻하다', 5),
 ('끊다', 5),
 ('부하', 5),
 ('대단하다', 5),
 ('내러티브', 5),
 ('떼다', 5),
 ('도르다', 5),
 ('대상', 5),
 ('로움', 5),
 ('심각하다', 5),
 ('남성', 5),
 ('디자인', 5),
 ('줄다', 5),
 ('누리다', 5),
 ('왠지', 5),
 ('대북', 5),
 ('선전', 5),
 ('낭만', 5),
 ('여기다', 5),
 ('얼렁뚱땅', 5),
 ('낮다', 5),
 ('쫒다', 5),
 ('실망', 5),
 ('건너', 5),
 ('치킨', 5),
 ('관점', 5),
 ('시기', 5),
 ('종종', 5),
 ('위성', 5),
 ('공백', 5),
 ('피다', 5),
 ('결정', 5),
 ('지는', 5),
 ('착각', 5),
 ('오글거리다', 5),
 ('무게', 5),
 ('흥미', 5),
 ('날다', 5),
 ('상징', 5),
 ('노리다', 5),
 ('나서다', 5),
 ('쫓아오다', 5),
 ...]

In [ ]:
# 각 리뷰별로 불용어 제거 적용
reviews['processed'] = reviews['감상평'].apply(lambda x: " ".join([word for word in okt.morphs(x, stem=True) if word not in stopwords and len(word) > 1]))


reviews

,Index,감상평,별점,공감수,processed
0,1,죽음이 아닌 의미 없는 삶을 두려워 하라,5.0,0,죽음 의미 두렵다 하라
1,2,규남이가 귀남이가 됐다가 추남이 되는 이야기,4.0,0,추남 이야기
2,3,둘의 관계가 굉장해 엄청나 사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 극장에...,3.5,0,관계 굉장하다 엄청나다 사운드 아주 풍부하다 몰입 좋다 극장
3,4,규남아 그래서 무슨 사랑을 했냐고 묻잔 아 대답해,3.0,0,남아 사랑 묻다 대답
4,5,재미도 없고 말도 안 되고 결말도 스토리도 너무 뻔한 영화,1.5,0,재미 결말 스토리 뻔하다
...,...,...,...,...,...
2830,2850,짧은 러닝 타임과 함께 킬링 타임할 수 있을지,별점없음,2,짧다 러닝 타임 킬링 타임
2831,2851,기대감이 아주 높아용,보고싶어요,0,대감 아주 높다
2832,2852,현재의 선택이 틀리지 않았음을 증명하라 구 교환 배우는 장난 아니네 그리고 감독님 ...,3.5,8,현재 선택 틀리다 증명 교환 배우다 장난 감독 힘들다 양화대교 노래 힘내다 선방 작...
2833,2853,놀애 잘앙 돌위아가 삼진아웃 반 외 엇덯해 이재훈과 구갼을 꼬셨슴니까,보고싶어요,0,놀애 자다 돌위 아가 삼진아웃 엇덯해 이재훈 구갼 꼬셨슴 니까
2834,2854,구 교환은 추격 장인,3.5,0,교환 추격 장인

In [ ]:
# '별점없음', '보고싶어요' 등 문자 데이터를 제외하고 숫자로 변환
df = reviews[~reviews['별점'].isin(['별점없음', '보고싶어요', '보는 중'])]
df['별점'] = pd.to_numeric(df['별점'], errors='coerce')
df

<ipython-input-38-0912859480be>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['별점'] = pd.to_numeric(df['별점'], errors='coerce')

,Index,감상평,별점,공감수,processed
0,1,죽음이 아닌 의미 없는 삶을 두려워 하라,5.0,0,죽음 의미 두렵다 하라
1,2,규남이가 귀남이가 됐다가 추남이 되는 이야기,4.0,0,추남 이야기
2,3,둘의 관계가 굉장해 엄청나 사운드가 아주 풍부한 영화라 몰입감이 좋기 때문에 극장에...,3.5,0,관계 굉장하다 엄청나다 사운드 아주 풍부하다 몰입 좋다 극장
3,4,규남아 그래서 무슨 사랑을 했냐고 묻잔 아 대답해,3.0,0,남아 사랑 묻다 대답
4,5,재미도 없고 말도 안 되고 결말도 스토리도 너무 뻔한 영화,1.5,0,재미 결말 스토리 뻔하다
...,...,...,...,...,...
2826,2846,북한을 배경으로 한 청춘 이야기 한 게임 더 나 박카스 광고 감성도 겉은 치열한 데...,3.0,3,북한 배경 청춘 이야기 게임 박카스 광고 감성 치열하다 몽글몽글
2827,2847,자유를 향한 질주를 보여주는 과정이 차곡차곡 쌓아지기는 하지만 를 넘어서면서 살짝 ...,3.0,6,자유 질주 보여주다 과정 차곡차곡 쌓다 지기 넘어서다 살짝 물음표 근래 상업 짧다 ...
2828,2848,그 모든 부분에서 딥하게 가지 못한 다 남는 것은 의 양화대교 뿐,2.5,22,양화대교
2832,2852,현재의 선택이 틀리지 않았음을 증명하라 구 교환 배우는 장난 아니네 그리고 감독님 ...,3.5,8,현재 선택 틀리다 증명 교환 배우다 장난 감독 힘들다 양화대교 노래 힘내다 선방 작...
2834,2854,구 교환은 추격 장인,3.5,0,교환 추격 장인

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 데이터프레임 예시 (이미 존재하는 데이터프레임 df)
# df = pd.read_csv('your_file.csv')  # 데이터프레임 로드하는 부분

# 별점 라벨 인코딩을 위해 값 변환
df['별점'] = df['별점'].astype(float)

# 라벨 인코더 초기화
label_encoder = LabelEncoder()

# 별점 라벨 인코딩 (0.5 -> 1, 1.0 -> 2, ..., 5.0 -> 10)
df['별점_encoded'] = label_encoder.fit_transform(df['별점']) + 1  # 라벨 인코딩 결과가 0부터 시작하므로 +1

df['별점_encoded'].unique()

array([10,  8,  7,  6,  3,  4,  5,  9,  2,  1])

# processed 파일 import

In [50]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving 그녀가 죽었다_processed.csv to 그녀가 죽었다_processed.csv

In [51]:
title = '그녀가 죽었다'
df = pd.read_csv(f'{title}_processed.csv')
df.head()

,Index,processed,별점,감상평
0,1,사이코 라이 구도 숭맹숭 초반 긴장감 마지막 이상하다 풀다 버리다 소재 재밌다 쌓다...,2.0,걍 사이코 대 또라이 구도로 가지\n한 명이 너무 밍숭맹숭 해졌다\n꼭 초반의 긴장...
1,2,처음 느껴지다 소재 반짝임 지키다,3.0,처음부터 느껴진 소재의 반짝임을 꽤나 지켜냈다할까.
2,3,결말 궁금하다 마지막 보기 완료 피해자 가해자 마음 착하다,3.0,24/10/18\n결말이 궁금하여 마지막 부분 보기 완료. 피해자인척 말고 언제든 ...
3,4,빼다 가볍다 보기 좋다,3.0,뇌빼고 가볍게 보기 좋음
4,5,관객 응시 연출 좋다,3.0,관객을 응시하는 연출이 좋았다

In [52]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 데이터프레임 예시 (이미 존재하는 데이터프레임 df)
# df = pd.read_csv('your_file.csv')  # 데이터프레임 로드하는 부분

# 별점 라벨 인코딩을 위해 값 변환
df['별점'] = df['별점'].astype(float)

# 라벨 인코더 초기화
label_encoder = LabelEncoder()

# 별점 라벨 인코딩 (0.5 -> 1, 1.0 -> 2, ..., 5.0 -> 10)
df['별점_encoded'] = label_encoder.fit_transform(df['별점']) + 1  # 라벨 인코딩 결과가 0부터 시작하므로 +1

df['별점_encoded'].unique()

array([ 4,  6,  2,  5,  1,  8,  9,  7,  3, 10])

# 로지스틱 회귀

In [40]:
#!pip install xlsxwriter

Collecting xlsxwriter
  Downloading XlsxWriter-3.2.0-py3-none-any.whl.metadata (2.6 kB)
Downloading XlsxWriter-3.2.0-py3-none-any.whl (159 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.9/159.9 kB 4.6 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.0

In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from google.colab import files

# 데이터프레임 정렬 (Index를 기준으로 오름차순 정렬)
df = df.sort_values(by='Index', ascending=True)

# NaN 값을 빈 문자열로 대체
df['processed'] = df['processed'].fillna('')

# train/test set 나누기 (최근 40%를 test set으로 사용)
split_index = int(len(df) * 0.6)
train_df = df.iloc[:split_index]
test_df = df.iloc[split_index:]

# TF-IDF 벡터화 (processed 텍스트)
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(train_df['processed'])
X_test = vectorizer.transform(test_df['processed'])

# 종속 변수 (별점_encoded)
y_train = train_df['별점_encoded']
y_test = test_df['별점_encoded']

# 로지스틱 회귀 모델 훈련
model = LogisticRegression(max_iter=1000, multi_class='multinomial', solver='lbfgs')
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 결과 평가
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, output_dict=True)

# classification report를 데이터프레임으로 변환
report_df = pd.DataFrame(report).transpose()

# y_pred에 0.5를 곱해 '예측 별점' 생성
df_test = test_df.copy()  # test 데이터 복사
df_test['예측 별점'] = y_pred * 0.5  # 예측된 값에 0.5 곱해서 실제 별점으로 변환

# 'gap' 열 생성 (실제 별점 - 예측 별점)
df_test['gap'] = df_test['별점'] - df_test['예측 별점']

# df_final에서 '별점_encoded' 열 제거 및 필요한 열 순서 지정
df_final = df_test.drop(columns=['별점_encoded'])
df_final = df_final[['Index', '감상평', '별점', '예측 별점', 'gap']]

# xlsx 파일명 생성
file_name = f"{title}_로지스틱_평점분류예측.xlsx"

# 여러 시트를 가진 Excel 파일로 저장
with pd.ExcelWriter(file_name, engine='xlsxwriter') as writer:
    df_final.to_excel(writer, sheet_name='Prediction Results', index=False)  # 첫 번째 시트에 저장
    report_df.to_excel(writer, sheet_name='Classification Report')  # 두 번째 시트에 저장

# 저장한 파일 다운로드
files.download(file_name)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Decision Tree 분류

In [54]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score
from google.colab import files

# 데이터프레임 정렬 (Index를 기준으로 오름차순 정렬)
df = df.sort_values(by='Index', ascending=True)

# NaN 값을 빈 문자열로 대체
df['processed'] = df['processed'].fillna('')

# train/test set 나누기 (최근 40%를 test set으로 사용)
split_index = int(len(df) * 0.6)
train_df = df.iloc[:split_index]
test_df = df.iloc[split_index:]

# TF-IDF 벡터화 (processed 텍스트)
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(train_df['processed'])
X_test = vectorizer.transform(test_df['processed'])

# 종속 변수 (별점_encoded)
y_train = train_df['별점_encoded']
y_test = test_df['별점_encoded']

# Decision Tree 모델 훈련
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 결과 평가
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, output_dict=True)

# classification report를 데이터프레임으로 변환
report_df = pd.DataFrame(report).transpose()

# y_pred에 0.5를 곱해 '예측 별점' 생성
df_test = test_df.copy()  # test 데이터 복사
df_test['예측 별점'] = y_pred * 0.5  # 예측된 값에 0.5 곱해서 실제 별점으로 변환

# 'gap' 열 생성 (실제 별점 - 예측 별점)
df_test['gap'] = df_test['별점'] - df_test['예측 별점']

# df_final에서 '별점_encoded' 열 제거 및 필요한 열 순서 지정
df_final = df_test.drop(columns=['별점_encoded'])
df_final = df_final[['Index', '감상평', '별점', '예측 별점', 'gap']]

# xlsx 파일명 생성
file_name = f"{title}_DecisionTree_평점분류예측.xlsx"

# 여러 시트를 가진 Excel 파일로 저장
with pd.ExcelWriter(file_name, engine='xlsxwriter') as writer:
    df_final.to_excel(writer, sheet_name='Prediction Results', index=False)  # 첫 번째 시트에 저장
    report_df.to_excel(writer, sheet_name='Classification Report')  # 두 번째 시트에 저장

# 저장한 파일 다운로드
files.download(file_name)

# SVM

In [55]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from google.colab import files

# 데이터프레임 정렬 (Index를 기준으로 오름차순 정렬)
df = df.sort_values(by='Index', ascending=True)

# NaN 값을 빈 문자열로 대체
df['processed'] = df['processed'].fillna('')

# train/test set 나누기 (최근 40%를 test set으로 사용)
split_index = int(len(df) * 0.6)
train_df = df.iloc[:split_index]
test_df = df.iloc[split_index:]

# TF-IDF 벡터화 (processed 텍스트)
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(train_df['processed'])
X_test = vectorizer.transform(test_df['processed'])

# 종속 변수 (별점_encoded)
y_train = train_df['별점_encoded']
y_test = test_df['별점_encoded']

# SVM 모델 훈련
model = SVC(kernel='linear', C=1, random_state=42)  # 선형 커널 사용
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 결과 평가
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, output_dict=True)

# classification report를 데이터프레임으로 변환
report_df = pd.DataFrame(report).transpose()

# y_pred에 0.5를 곱해 '예측 별점' 생성
df_test = test_df.copy()  # test 데이터 복사
df_test['예측 별점'] = y_pred * 0.5  # 예측된 값에 0.5 곱해서 실제 별점으로 변환

# 'gap' 열 생성 (실제 별점 - 예측 별점)
df_test['gap'] = df_test['별점'] - df_test['예측 별점']

# df_final에서 '별점_encoded' 열 제거 및 필요한 열 순서 지정
df_final = df_test.drop(columns=['별점_encoded'])
df_final = df_final[['Index', '감상평', '별점', '예측 별점', 'gap']]

# xlsx 파일명 생성
file_name = f"{title}_SVM_평점분류예측.xlsx"

# 여러 시트를 가진 Excel 파일로 저장
with pd.ExcelWriter(file_name, engine='xlsxwriter') as writer:
    df_final.to_excel(writer, sheet_name='Prediction Results', index=False)  # 첫 번째 시트에 저장
    report_df.to_excel(writer, sheet_name='Classification Report')  # 두 번째 시트에 저장

# 저장한 파일 다운로드
files.download(file_name)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))